let Comments = [
    {"nombre":"Corinne Sidebotham","rol":"Sales","comentario":"Quality Control Specialist"},
    {"nombre":"Rhys Rushton","rol":"Human Resources","comentario":"Business Systems Development Analyst"},
    {"nombre":"Cristine Surguine","rol":"Business Development","comentario":"VP Product Management"},
    {"nombre":"Darsey Cordelet","rol":"Accounting","comentario":"Nurse Practicioner"},
    {"nombre":"Charla Locarno","rol":"Engineering","comentario":"Nuclear Power Engineer"},
    {"nombre":"Abrahan Jelleman","rol":"Accounting","comentario":"Administrative Assistant IV"},
    {"nombre":"Wenona Iskowicz","rol":"Accounting","comentario":"Nuclear Power Engineer"},
    {"nombre":"Tobit Lerven","rol":"Training","comentario":"Nuclear Power Engineer"},
    {"nombre":"Merrick Lafont","rol":"Research and Development","comentario":"Mechanical Systems Engineer"},
    {"nombre":"Che Cleveland","rol":"Training","comentario":"Software Consultant"},
    {"nombre":"Valentine Swinbourne","rol":"Marketing","comentario":"Civil Engineer"},
    {"nombre":"Zara Stirley","rol":"Human Resources","comentario":"Desktop Support Technician"},
    {"nombre":"Lodovico Ouslem","rol":"Legal","comentario":"Accounting Assistant IV"},
    {"nombre":"Lynnea Curtiss","rol":"Training","comentario":"Help Desk Technician"},
    {"nombre":"Shelby Kindred","rol":"Product Management","comentario":"Nurse Practicioner"},
    {"nombre":"Wat Greson","rol":"Services","comentario":"Dental Hygienist"},
    {"nombre":"Kathye Bartoleyn","rol":"Business Development","comentario":"Registered Nurse"},
    {"nombre":"Cris Shirland","rol":"Research and Development","comentario":"Design Engineer"},
    {"nombre":"Quinton Drinkall","rol":"Accounting","comentario":"Web Developer III"},
    {"nombre":"Fleming Norley","rol":"Business Development","comentario":"Human Resources Assistant III"},
    {"nombre":"Lew Edelman","rol":"Research and Development","comentario":"Financial Analyst"},
    {"nombre":"Ronica Troutbeck","rol":"Training","comentario":"Research Assistant IV"},
    {"nombre":"Seth Dresse","rol":"Product Management","comentario":"Programmer IV"},
    {"nombre":"Rosina Fishbie","rol":"Training","comentario":"Environmental Tech"},
    {"nombre":"Marion Fader","rol":"Research and Development","comentario":"Administrative Officer"},
    {"nombre":"Luelle Bullerwell","rol":"Business Development","comentario":"Analyst Programmer"},
    {"nombre":"Emanuele Yegorchenkov","rol":"Legal","comentario":"Human Resources Manager"},
    {"nombre":"Quinton Monteath","rol":"Research and Development","comentario":"Safety Technician II"},
    {"nombre":"Arabel Dryburgh","rol":"Services","comentario":"Design Engineer"},
    {"nombre":"Nell Blockley","rol":"Engineering","comentario":"Librarian"},
    {"nombre":"Marchall Dowzell","rol":"Business Development","comentario":"VP Quality Control"},
    {"nombre":"Jayme Nicklinson","rol":"Human Resources","comentario":"Research Associate"},
    {"nombre":"Trudie Arnett","rol":"Research and Development","comentario":"Staff Scientist"},
    {"nombre":"Felicity Lorkings","rol":"Services","comentario":"VP Quality Control"},
    {"nombre":"Nanon Arbon","rol":"Accounting","comentario":"Computer Systems Analyst III"},
    {"nombre":"Amil Pollitt","rol":"Legal","comentario":"Human Resources Assistant IV"},
    {"nombre":"Eleanore Houlaghan","rol":"Human Resources","comentario":"Systems Administrator I"},
    {"nombre":"Berk Bambrugh","rol":"Human Resources","comentario":"Software Test Engineer I"},
    {"nombre":"Mirilla Whitwood","rol":"Human Resources","comentario":"Technical Writer"},
    {"nombre":"Ruddie Vicar","rol":"Product Management","comentario":"Paralegal"},
    {"nombre":"Madelina Grier","rol":"Product Management","comentario":"Design Engineer"},
    {"nombre":"Cilka Mattek","rol":"Legal","comentario":"Compensation Analyst"},
    {"nombre":"Terri Georgiev","rol":"Support","comentario":"Structural Analysis Engineer"},
    {"nombre":"Eduino Castano","rol":"Marketing","comentario":"Information Systems Manager"},
    {"nombre":"Carol-jean Gibby","rol":"Product Management","comentario":"VP Quality Control"},
    {"nombre":"Jilli Butfield","rol":"Legal","comentario":"Project Manager"},
    {"nombre":"Barbie Kippie","rol":"Sales","comentario":"Social Worker"},
    {"nombre":"Paloma Snedker","rol":"Research and Development","comentario":"Administrative Officer"},
    {"nombre":"Aymer Brack","rol":"Training","comentario":"Nuclear Power Engineer"},
    {"nombre":"Meade Thurgood","rol":"Research and Development","comentario":"Staff Accountant I"}
]

export default Comments;
